### ISSUE TITLE
Bilibili Evolved 不能使用，是脚本不能联网吗？

### ISSUE THREAD

**Issue by 23Ben** [scriptscat/scriptcat#74]
Bilibili Evolved 不能使用，是脚本不能联网吗？油猴上使用都是正常的。
https://raw.githubusercontent.com/the1812/Bilibili-Evolved/master/dist/bilibili-evolved.user.js

**Comment by CodFrm** [comment]
没问题的，你的浏览器版本是多少呢？

最近发现在低内核的版本上运行有问题，还没解决

**Comment by 23Ben** [comment]
brave浏览器  1.39.111  Chromium: 102.0.5005.61

**Comment by CodFrm** [comment]
> brave浏览器 1.39.111 Chromium: 102.0.5005.61

应该是可以的，可以看看页面上的f12有没有错误提示么？

**Comment by 23Ben** [comment]
Bilibili Evolved.user.js:57 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'once')
    at 3420 (Bilibili Evolved.user.js:57:73346)
    at __webpack_require__ (Bilibili Evolved.user.js:95:77512)
    at 7177 (Bilibili Evolved.user.js:57:68931)
    at Function.__webpack_require__ (Bilibili Evolved.user.js:95:77512)
    at async Bilibili Evolved.user.js:95:79369
3420 @ Bilibili Evolved.user.js:57
__webpack_require__ @ Bilibili Evolved.user.js:95
7177 @ Bilibili Evolved.user.js:57
__webpack_require__ @ Bilibili Evolved.user.js:95
await in __webpack_require__ (async)
(anonymous) @ Bilibili Evolved.user.js:97
(anonymous) @ Bilibili Evolved.user.js:97
(anonymous) @ Bilibili Evolved.user.js:97
window.erwtDniQYHdxHDrm @ Bilibili Evolved.user.js:99
set @ VM278:2
(anonymous) @ Bilibili Evolved.user.js:1
(anonymous) @ VM279:6
(anonymous) @ VM279:8
BV1a5411Q7jk:294          GET https://s1.hdslb.com/bfs/seed/log/report/log-reporter.js net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/vue.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/static/jinkela/long/js/sentry/bundle.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
stardust-video.93d947938b104dae6de940fa5a0ab194b8ec9659.js:1                      //         \\         //          \\       //    ##DDDDDDDDDDDDDDDDDDDDDD##    ## DDDDDDDDDDDDDDDDDDDD ##   ________   ___   ___        ___   ________   ___   ___        ___    ## hh                hh ##   |\   __  \ |\  \ |\  \      |\  \ |\   __  \ |\  \ |\  \      |\  \    ## hh    //    \\    hh ##   \ \  \|\ /_\ \  \\ \  \     \ \  \\ \  \|\ /_\ \  \\ \  \     \ \  \    ## hh   //      \\   hh ##    \ \   __  \\ \  \\ \  \     \ \  \\ \   __  \\ \  \\ \  \     \ \  \    ## hh                hh ##     \ \  \|\  \\ \  \\ \  \____ \ \  \\ \  \|\  \\ \  \\ \  \____ \ \  \    ## hh      wwww      hh ##      \ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\\ \_______\\ \__\    ## hh                hh ##       \|_______| \|__| \|_______| \|__| \|_______| \|__| \|_______| \|__|    ## MMMMMMMMMMMMMMMMMMMM ##    ##MMMMMMMMMMMMMMMMMMMMMM##                             Release 2.64.1. Powered by jinkela-core 2.8.10.         \/            \/
DevTools failed to load source map: Could not load content for https://s1.hdslb.com/bfs/seed/jinkela/header-v2/international-header-89feb61739a4fb44e743bb6e5cefabfa4bf47897-header.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
nc-loader-2.6.7.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'addIceCandidate')
    at I (nc-loader-2.6.7.min.js:2:355865)
    at he.window (nc-loader-2.6.7.min.js:2:375969)
    at Module.<anonymous> (nc-loader-2.6.7.min.js:2:376737)
    at r (nc-loader-2.6.7.min.js:2:146)
    at Object.<anonymous> (nc-loader-2.6.7.min.js:2:130633)
    at r (nc-loader-2.6.7.min.js:2:146)
    at nc-loader-2.6.7.min.js:2:945
    at t (nc-loader-2.6.7.min.js:2:955)
    at nc-loader-2.6.7.min.js:2:380155
I @ nc-loader-2.6.7.min.js:2
he.window @ nc-loader-2.6.7.min.js:2
(anonymous) @ nc-loader-2.6.7.min.js:2
r @ nc-loader-2.6.7.min.js:2
(anonymous) @ nc-loader-2.6.7.min.js:2
r @ nc-loader-2.6.7.min.js:2
(anonymous) @ nc-loader-2.6.7.min.js:2
t @ nc-loader-2.6.7.min.js:2
(anonymous) @ nc-loader-2.6.7.min.js:2

**Comment by CodFrm** [comment]
感觉是网络的问题，最近因为jsdelivr被屏蔽了，安装的时候可能require获取失败，这块应该做个错误通知

哥哥挂梯子之类的，把脚本删除重新安装试试。当初安装的时候应该很慢吧
